language: java
jdk:
  - oraclejdk8
script: ./bin/build.sh
branches:
  only:
    - develop
notifications:
  email:
    recipients:
      - btrplace-ci@googlegroups.com
    on_success: always
    on_failure: always
