language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: JBVFH+9DpoDcxdKapZWk3UzAN6JxeOwe0y6G6CvvuAmQmI06YuEZpT9os3M1fAz6gnhtlj2JelsqZlrgX5Tr4BvAqwRFz35zcAnkz1r3YDy9RV6j013qcikrw/nV3HJTDCghx1LxET/akpGPqbWEzCToebxI5S8wJ+pkq9QkAZU=
  - secure: PrZBfWtKBgxbZRGlXqtz54XJhf0XiirbBz7YQkCaI94jM9QMPERaW25igigW7kx9+t1TuOym/3YoYiGxgArqnMkXByM2bYUbY6DkG7rdE/xH8RMrbuq0A3WGuCWMH38WsCMt3AA1nOpdpjLWfMX0m1Vuy5nca+8B1xVoShh5WVs=
  - secure: rybuxazOQlxERPG0pem4SwlKU8jefe77nt+nUi8RqZKbWflYQ/sDSs9g+g3MZn2A7hFK5NbdO3Jg4JqzMoR+GiLqO3w7J21nEsslmDoJW3V/ixTa8vN/yVEwZ6qwvXQaJVn756MywrHQwZ/Cd/4CaB7UmcIq80NgUiN/9MxE8Mw=
before_install:
- openssl aes-256-cbc -K $encrypted_5a7f2daf798b_key -iv $encrypted_5a7f2daf798b_iv
  -in gpg.enc -out etc/gpg -d
- openssl aes-256-cbc -K $encrypted_5a7f2daf798b_key -iv $encrypted_5a7f2daf798b_iv
  -in deploy_apidocs.enc -out etc/deploy_apidocs -d
- openssl aes-256-cbc -K $encrypted_5a7f2daf798b_key -iv $encrypted_5a7f2daf798b_iv
  -in deploy.enc -out etc/deploy -d
- chmod 600 etc/deploy
- eval "$(ssh-agent)"
- ssh-add etc/deploy
- ssh-add etc/deploy_apidocs
- git config --global user.name "Build Bot"
- git config --global user.email "buildbot@btrplace.org"
- git remote add deploy git@github.com:btrplace/scheduler.git
- export MAVEN_OPTS=-Xmx512m
install:
- mvn -q install -DskipTests
script: ./bin/build.sh
branches:
  only:
  - master
  - release
notifications:
  email:
    recipients:
    - btrplace-ci@googlegroups.com
    on_success: always
    on_failure: always
