branches:
  only:
  - master
  - release
  - travis_dbg
env:
  global:
  - secure: PvNRVfXK/Mmyb8nA98rAKO9m2wYGCpEDHIQiM8sbtmyR0i4wXcaVXCYnvuMTl9nG1PTdhnm5mXH+Yau0m/OFCF56MGthurtWosCO6j+/dkoS7I01IpKsx/gZx2QCy2pAjs3cogTSONEmGuhKbfNbv1FEyvtJhneDD5CDtTAKkWE=
  - secure: QJ8eh/+F7g0M+FajUMW+QeKjw6oL4FkRFpkfeFOTAHZzqNhYAbZ8+A1RUKC92QpszB+trYc6qfJ5cyq+qWa7PeEo2QdvLkv9ST4yyFUDqZZAblHccDgo2Wz5acy/FB7jWY7438LCke4zwuoiOlxjUZ+qG8H578rGnK1oJW5Ux4s=
  - secure: X53nh1b3zjN/wA1M2pag+OvRy7Na3JhwtOf+XFd+byZGZDcYSJnmmwhcE7KycK5+OGcN87iJB3f3gqdeiX3fiEJnrSQc22sexMKDjdn5l6uBgDE+4Cequh3n4V8kA5ODcpWhpA+/QRIKyN0afbhPLygVPO9mVyFyTTCLpPuc68I=
  - secure: apZzObcTKp1Hqbs5lL8pKXsUDyy8xl9kG+LRREVOGcWQ33/qVF9DYljvvFHeOrH7nUghAGmEUwuhlLG0GYMy4zrGvM7DGAq0Sy/GwLTRgDC1LWQtyN9S92aqrwZmuwaUVW+U0EmBCcxvVKXY6hfpRCFAQJO+Emc3ophmBBEa4uI=
before_install:
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/gpg.enc -out etc/gpg -d
- eval "$(ssh-agent)"
- gpg --import etc/gpg
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/deploy_apidocs.enc -out etc/deploy_apidocs -d
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/deploy_scheduler.enc -out etc/deploy_scheduler -d
- chmod 600 etc/deploy*
- ssh-add etc/deploy*
- git config --global user.name "Build Bot"
- git config --global user.email "buildbot@btrplace.org"
- git remote add deploy git@github.com:btrplace/scheduler.git
- export MAVEN_OPTS=-Xmx512m
install:
- mvn -Dgpg.passphrase=${GPG_PASSPHRASE} dependency:resolve
jdk:
- oraclejdk8
language: java
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
    - btrplace-ci@googlegroups.com
script: ./bin/build.sh
