branches:
  only:
  - master
  - release
  - travis_dbg
env:
  global:
  - secure: VhKXa/vU5AZEa4NmHpu2nR+/5G2I3epnabhAMGPVWtWQ2+NwSKos0MV1z8SeJPp0d2yPDAadeYbor6Wf1QNEA93YDGWAV2MJvBNc8p3aw+5os1n4xvRVusmHCke52PCdhNP6TNXdqiNgbU0wHiv5daUjFF6x7YVWn9MZ8yIqLiM=
  - secure: bdsiQTi3h248+9Yj3S28paTDTvkNe+JcriYffchOxFJ05Oq0mv1AloUHxK6RqTLnyLtAmUingQLWWAMAxzoMYVyUrTdPE19/aiwIewrUbe1Q4KEOEoWOC2fTbkh4ISARGi0oHrjUKOevWerpv8TK40ozr1rqSrK9xU/8vtuiecY=
  - secure: gLGlJ0MdUEAUWY1mv/b5H6kh1UPFL30QYuTofBMOt9ewadNpep/LnZYQ4kcfopzr2ZlCA8MaQNH/lh1c6D8YKuoqGVW45LMPbbLaGOvPnAyivueSbmK+74NHm1DkTdOiA8vWjE9e84q1MAFbB73NKDbaIl16xHE3jYwYASXhFC0=
  - secure: mApNjQHkYsyguVnUep3SowBVX5PzIJtvIgWEJERlSFCweKumQTDaZdNAlTz24W21Lpr1JCJswK5SWzBD7cbC5W5Kmf3hPmwkHM26JgbUd8RIkunSsgmXQdeL4LoTN4jdjTZpobY+pZPEVLbjVjwQ52T7BKuK+fRwpI2Oi3J4yUo=
before_install:
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv -in etc/deploy_apidocs2.enc -out etc/deploy_apidocs2 -d
- gpg --import etc/gpg
- eval "$(ssh-agent)"
- chmod 600 etc/deploy etc/deploy_apidocs
- ssh-add etc/deploy
- ssh-add etc/deploy_apidocs2
- git config --global user.name "Build Bot"
- git config --global user.email "buildbot@btrplace.org"
- git remote add deploy git@github.com:btrplace/scheduler.git
- export MAVEN_OPTS=-Xmx512m
install:
- mvn -Dgpg.passphrase=${GPG_PASSPHRASE} dependency:resolve
jdk:
- oraclejdk8
language: java
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
    - btrplace-ci@googlegroups.com
script: ./bin/build.sh
