branches:
  only:
  - master
  - release
  - travis_dbg
env:
  global:
  - secure: aJY93F6edWa3yuf+tDAk8aylBSbDXB/gHqJCeSUJFcmhrinjotsfkuQ9oQjk8KQID3Pj/X+7iSdiV0gRBbvkkj18xHfRygJOgjPaWE7oko5pGgXxDAUSTPj7o6mitJQejwabFQmeDn/zHMS0sRBEgyqsIlxUdm+c1aV8uUmjOSI=
  - secure: IqJKHyuJwAQFiKogN3ed/jXYloVIoFPeO5CcRgLghpd2xFfyThql02hOdVtvKwrA0uiMf588j4AToIWRPdoBJtl0LnIpIrkBdYKj2eq1SEm+u3cIq8YWchJdAq0NuGUrD+b48FGuSWkYNATF/MOSSB8DPKEWmHEPjfSlPqNMLuI=
  - secure: iwOk6McxhScuYCpiQjRsaaw0Nl3W2RlDgXX7Vn1ahrFsRR+VPsJrXJ++L/pnOfNxv5ULJlrgePOkRAHdac/ZjkLUeFrT8NeIJ504XfQ6xi247mxhNbDDdz61Oo1eZNyXVitTVnAZhkXxbzIfd6qJSmNwAR8q/F1R54XKtGRiyuo=
  - secure: mR+au4x2VVjNfDXzZqSPylRxzbU727U0PuLSZqfz1xlIksPL/pYLIgHv4E0kTepTRg+HqqHGzJoX+kq7pQJKLpUV+SkbSCRZPNV4oX9jsnuvUD9AobQYprFhHGbS0Nfhi8fqJcUh3dviyTvgCGZYgqA5BCTdy/QzYccjGBwFSXI=
before_install:
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/gpg.enc -out etc//gpg -d
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/deploy_apidocs.enc -out etc/deploy_apidocs -d
- openssl aes-256-cbc -K $encrypted_e836d0488b25_key -iv $encrypted_e836d0488b25_iv
  -in etc/deploy_scheduler.enc -out etc/deploy_scheduler -d
- eval "$(ssh-agent)"
- gpg --import etc/gpg
- chmod 600 etc/deploy*
- ssh-add etc/deploy*
- git config --global user.name "Build Bot"
- git config --global user.email "buildbot@btrplace.org"
- git remote add deploy git@github.com:btrplace/scheduler.git
- export MAVEN_OPTS=-Xmx512m
install:
- mvn -Dgpg.passphrase=${GPG_PASSPHRASE} dependency:resolve
jdk:
- oraclejdk8
language: java
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
    - btrplace-ci@googlegroups.com
script: ./bin/build.sh
